### ISSUE TITLE
Reporting a "Peep had a problem"

### ISSUE THREAD

**Issue by emxjay** [erikrose/peep#117]
Here we go:

```
peep: (3, 0, 0)
python: '2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2]'
pip: '1.5.4'
Command line:  ['/tmp/tmp.JJvxyhntFf/peep.py', 'install', '-r', '/tmp/tmp.JJvxyhntFf/letsencrypt-auto-requirements.txt']
Traceback (most recent call last):
  File "/tmp/tmp.JJvxyhntFf/peep.py", line 958, in <module>
    exit(main())
  File "/tmp/tmp.JJvxyhntFf/peep.py", line 930, in main
    return commands[argv[1]](argv[2:])
  File "/tmp/tmp.JJvxyhntFf/peep.py", line 862, in peep_install
    for path in req_paths))
  File "/tmp/tmp.JJvxyhntFf/peep.py", line 862, in <genexpr>
    for path in req_paths))
  File "/tmp/tmp.JJvxyhntFf/peep.py", line 839, in downloaded_reqs_from_path
    _parse_requirements(path, finder)]
  File "/tmp/tmp.JJvxyhntFf/peep.py", line 420, in __init__
    self.__class__ = self._class()
  File "/tmp/tmp.JJvxyhntFf/peep.py", line 699, in _class
    if self._actual_hash() not in self._expected_hashes():
  File "/tmp/tmp.JJvxyhntFf/peep.py", line 329, in memoizer
    self._cache[func.__name__] = func(self)
  File "/tmp/tmp.JJvxyhntFf/peep.py", line 655, in _actual_hash
    return hash_of_file(join(self._temp_path, self._downloaded_filename()))
  File "/tmp/tmp.JJvxyhntFf/peep.py", line 329, in memoizer
    self._cache[func.__name__] = func(self)
  File "/tmp/tmp.JJvxyhntFf/peep.py", line 608, in _downloaded_filename
    link = self._link() or self._finder.find_requirement(self._req, upgrade=False)
  File "/home/<REMOVED>/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for argparse==1.4.0 (from -r /tmp/tmp.JJvxyhntFf/letsencrypt-auto-requirements.txt (line 7))
```

FYI, that happened when I was trying to install [Let's Encrypt](https://github.com/letsencrypt/letsencrypt) on an Ubuntu 14.04.3 LTS.

**Comment by erikrose** [comment]
If you try again, does it work? I suspect a network failure of some kind, since argparse is the first requirement in the file. If not, does `pip install argparse==1.4.0` fail with a similar kind of error? (Don't `sudo pip install`, as that will mess with your global Python environment.) Thanks for the report!

**Comment by edmorley** [comment]
It's also worth noting that argparse isn't needed on Python 2.7 -- the letsencrypt-auto script should only be including it on Python 2.6 really:
https://github.com/letsencrypt/letsencrypt/blob/5f0641bccbdc155c36c626e78f29508b696c2ff8/letsencrypt-auto-source/letsencrypt-auto#L444

**Comment by edmorley** [comment]
Though I guess actually the real bug here is that peep is giving a "Peep had a problem" for a `DistributionNotFound`?

**Comment by erikrose** [comment]
Yes, that's a little silly.

**Comment by edmorley** [comment]
#118 makes peep not output the misleading "please file an issue" banner for failures like these, since they aren't peep's fault. Thank you for reporting so we could make the behaviour here clearer :-)

Regarding the original issue, I seem to recall one of our project's contributors seeing similar errors when behind a proxy and/or using an old version of pip? If retrying as suggested by Erik doesn't work, I'd manually run `pip install -r argparse==1.4.0 --verbose` to see if that gives any more clues and/or trying a newer version of pip. Failing that, maybe file an issue on the LetsEncrypt repo and see if they have any ideas :-)
