### ISSUE TITLE
letsencrypt-auto failed

### ISSUE THREAD

**Issue by rgeist** [erikrose/peep#120]
Hello, i tried to re-install the letsencrypt-certificate to my apache/debian system using the following commands:

cd /opt/letsencrypt
git pull
./letsencrypt-auto --apache -d www.geisterwolke.de -d rgst02.synserver.de

The Error Message I get ist this:

Command /root/.local/share/letsencrypt/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-lkvWHu-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('
', '
'), __file__, 'exec'))" install --record /tmp/pip-9vHfqW-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/.local/share/letsencrypt/include/site/python2.7 failed with error code 1 in /tmp/pip-lkvWHu-build

Oh no! Peep had a problem while trying to do stuff. Please write up a bug report
with the specifics so we can fix it:

https://github.com/erikrose/peep/issues/new

Here are some particulars you can copy and paste into the bug report:

---
peep: (3, 0, 0)
python: '2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2]'
pip: '1.5.6'
Command line:  ['/tmp/tmp.5fj0uX33xp/peep.py', 'install', '-r', '/tmp/tmp.5fj0uX33xp/letsencrypt-auto-requirements.txt']
Traceback (most recent call last):
  File "/tmp/tmp.5fj0uX33xp/peep.py", line 958, in <module>
    exit(main())
  File "/tmp/tmp.5fj0uX33xp/peep.py", line 930, in main
    return commands[argv[1]](argv[2:])
  File "/tmp/tmp.5fj0uX33xp/peep.py", line 882, in peep_install
    req.install()
  File "/tmp/tmp.5fj0uX33xp/peep.py", line 650, in install
    run_pip(['install'] + other_args + ['--no-deps', '-U', archive_path])
  File "/tmp/tmp.5fj0uX33xp/peep.py", line 204, in run_pip
    status_code = pip.main(initial_args)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/__init__.py", line 248, in main
    return command.main(cmd_args)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/basecommand.py", line 161, in main
    text = '
'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 54: ordinal not in range(128)

**Comment by edmorley** [comment]
This is an issue with pip rather than peep (contrary to what the output tries to imply :-)), it would seem there are a number of issues in pip's tracker related to this:
https://github.com/pypa/pip/issues?q=is%3Aissue+unicodeDecodeError

It appears that setting `LC_ALL=C` in the environment you may be able to work around this pip bug:
http://stackoverflow.com/questions/26473681/pip-install-numpy-throws-an-error-ascii-codec-cant-decode-byte-0xe2#comment41585583_26473681

If that fixes the problem, could you file an issue against the letsencrypt tracker to add this to their FAQs?

Closing this since it's either an issue with pip or letsencrypt's bootstrapping process, rather than peep :-)

**Comment by rgeist** [comment]
Sorry for writing to the wrong tracker, I used the address given in the error message of the letsencrypt-script.

**Comment by edmorley** [comment]
Yeah it's not your fault - the message really was misleading! At least that part should be fixed soon :-)

**Comment by edmorley** [comment]
> At least that part should be fixed soon :-)

Actually I tell a lie, #118 didn't cover `UnicodeDecodeError()`.
I've filed #122 for making sure peep doesn't show this misleading "file an issue" error for this case.
